Milestonethree
cgcarlosg/friendship pull request #3
Opened 2021-01-29 21:00 UTC by cgcarlosg

The method saves, in the friendship model, creates two rows
using a call -back, after_save to create a second record after saving a friendship (using user_id and friend_id in inverse order)
user_id and friend_id is unique

2021-01-30 02:26 UTC, MarilenaRoque requested changes
Hello @cgcarlosg! :rocket:

## Congratulations on your work on this milestone, so far! Almost all features are implemented smoothly! 👏🏻 

However, there are a few details to adjust before the approval.

# Changes Requested :recycle:

- [ ] Posts timeline includes posts written by logged-in user and their friends.
- Remember that we have a model of mutual friendship. It means that once a friendship is confirmed, no matter who sent the invitation, both should see each other posts in their timelines. Right now, only the one that sent the invitation (the one represented in the column user_id in the friendship) can see the post of his friends. Make sure to combine queries to get the friend's posts where the current user is user_id and also where he is the friend_id.

- [ ] Unit and Integration tests!
- Please, add more unit and integration tests, including all your models.

- [ ] Fix misspelled command to run your tests on README.md

That is all. Feel free to contact me on Slack if you need any further information.

Happy Coding!!! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

2021-01-30 13:14 UTC, blackpintz requested changes
# Status: Changes Required 🛑 

## Hello team 👋,

**Great job implementing the requested changes 👏. However, there are still a few requirements needed.**

1).**So I have two users, Jen and Mercy. When Jen clicks the add friend button next to Mercy's name, then after the button is removed there should be a sentence reading pending status or something, next to Mercy's name. After they are confirmed friends, it should read Friends next to their names. See an example in the screenshot below.**

 before a request is sent  | After a request is sent
 ---------------------------| ------------------------
![before_request](https://user-images.githubusercontent.com/38922385/105225595-dd771b00-5b6f-11eb-9aff-d3efa75d4c23.png) | ![after_request](https://user-images.githubusercontent.com/38922385/105225626-e831b000-5b6f-11eb-8a78-1f6e4ad167ca.png)**

2). **You have not used the correct directory structure for the spec tests. Model tests should be in `spec/models` directory and feature tests should be `spec/features` directory.**

3). **Add tests for associations and methods defined in all your models. Hint you can use [Shoulda Matchers](http://matchers.shoulda.io/docs/v4.0.1/Shoulda/Matchers/ActiveRecord.html#belong_to-instance_methodl). If a method is not used outside a class, you can declare it private and not write a test for it.**
4). **Add feature tests for when you create a post, comment on a post and like a post.**
5). **See on more in the comment below.**

## Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

2021-01-30 13:14 UTC, blackpintz commented on spec/friendrequest_spec.rb
> +    it 'create invalid friendship' do
You cannot write tests for multiple classes in one file. `User` class tests should be written in `user_spec.rb` and `Friendship` class tests in `friendship_spec.rb`.

2021-01-31 03:03 UTC, MarilenaRoque approved these changes
## Congratulations !!! 🎉 

# Project Approved! ✔️ 

You can merge it, and go on with the next milestone!!!

As always, Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

2021-01-31 12:02 UTC, merged